#!/bin/bash

# Volunteer Connect - Production Deployment Script for Hostinger
# This script helps deploy the application to Hostinger server

echo "🚀 Volunteer Connect - Production Deployment"
echo "=============================================="
echo ""

# Server details
SERVER_IP="157.173.214.77"
SERVER_PORT="65002"
SERVER_USER="u605696782"
SERVER_PASS="Volunteer@@123"

# Database details
DB_HOST="mysql"
DB_USER="u605696782_volunteer"
DB_PASS="Volunteer@@123"
DB_NAME="u605696782_volunteer"

echo "📋 Deployment Steps:"
echo "1. Upload files to server"
echo "2. Install dependencies"
echo "3. Setup database"
echo "4. Configure environment"
echo "5. Start services"
echo ""

echo "⚠️  Note: This script provides commands to run manually on the server."
echo "   Due to SSH password authentication, you'll need to run these commands"
echo "   directly on the Hostinger server via SSH or hPanel terminal."
echo ""

echo "📝 Commands to run on Hostinger server:"
echo "========================================"
echo ""
echo "# 1. Navigate to your project directory (usually ~/domains/volunteerconnect.io/public_html or similar)"
echo "cd ~/domains/volunteerconnect.io/public_html || cd ~/public_html"
echo ""
echo "# 2. Create project structure"
echo "mkdir -p backend frontend"
echo ""
echo "# 3. Upload your project files (use FTP/SFTP or git)"
echo "# Option A: Using Git (if you have a repository)"
echo "# git clone https://your-repo-url.git ."
echo ""
echo "# Option B: Upload files via FTP/SFTP to the server"
echo ""
echo "# 4. Navigate to backend and install dependencies"
echo "cd backend"
echo "npm install --production"
echo ""
echo "# 5. Create .env file"
echo "cat > .env << 'EOF'"
echo "PORT=3000"
echo "NODE_ENV=production"
echo "DB_HOST=mysql"
echo "DB_USER=$DB_USER"
echo "DB_PASSWORD=$DB_PASS"
echo "DB_NAME=$DB_NAME"
echo "DB_PORT=3306"
echo "JWT_SECRET=\$(node -e \"console.log(require('crypto').randomBytes(32).toString('base64'))\")"
echo "JWT_EXPIRE=7d"
echo "CORS_ORIGIN=https://volunteerconnect.io"
echo "EOF"
echo ""
echo "# 6. Run database migrations"
echo "npm run migrate"
echo ""
echo "# 7. Install PM2 globally (if not installed)"
echo "npm install -g pm2"
echo ""
echo "# 8. Start backend server with PM2"
echo "pm2 start server.js --name volunteerconnect-api"
echo "pm2 save"
echo "pm2 startup"
echo ""
echo "# 9. Build frontend (on your local machine first, then upload build folder)"
echo "# On local machine:"
echo "# cd frontend"
echo "# npm install"
echo "# npm run build"
echo "# Then upload the 'build' folder contents to public_html"
echo ""
echo "✅ Deployment complete!"
echo ""
echo "🔍 Verify deployment:"
echo "- API: https://volunteerconnect.io/api/health"
echo "- API Docs: https://volunteerconnect.io/api-docs"
echo "- Frontend: https://volunteerconnect.io"

